// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"review-job/internal/biz"
	"review-job/internal/conf"
	"review-job/internal/data"
	"review-job/internal/job"
	"review-job/internal/server"
	"review-job/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, kafka *conf.Kafka, elasticsearch *conf.Elasticsearch, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	reader, err := job.NewKafkaReader(kafka)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	esClient, err := job.NewESClient(elasticsearch)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	helper := job.NewLoggerHelper(logger)
	jobWorker := job.NewJobWorker(reader, esClient, helper)
	app := newApp(logger, grpcServer, httpServer, jobWorker)
	return app, func() {
		cleanup()
	}, nil
}
