// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"review-O/internal/biz"
	"review-O/internal/conf"
	"review-O/internal/data"
	"review-O/internal/server"
	"review-O/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, registry)
	if err != nil {
		return nil, nil, err
	}
	reviewForward := data.NewReviewForwardRepo(dataData)
	operationUsecase := biz.NewOperationUsecase(reviewForward, logger)
	operationService := service.NewOperationService(operationUsecase)
	grpcServer := server.NewGRPCServer(confServer, operationService, logger)
	httpServer := server.NewHTTPServer(confServer, operationService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
