// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: operation/v1/operation.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditReviewRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ReviewID int64                  `protobuf:"varint,1,opt,name=reviewID,proto3" json:"reviewID,omitempty"`
	// 1=通过 2=驳回（与 review-service 一致）
	Result        int32  `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	Remark        string `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator      string `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditReviewRequest) Reset() {
	*x = AuditReviewRequest{}
	mi := &file_operation_v1_operation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditReviewRequest) ProtoMessage() {}

func (x *AuditReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_v1_operation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditReviewRequest.ProtoReflect.Descriptor instead.
func (*AuditReviewRequest) Descriptor() ([]byte, []int) {
	return file_operation_v1_operation_proto_rawDescGZIP(), []int{0}
}

func (x *AuditReviewRequest) GetReviewID() int64 {
	if x != nil {
		return x.ReviewID
	}
	return 0
}

func (x *AuditReviewRequest) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *AuditReviewRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *AuditReviewRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

type AuditReviewReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewID      int64                  `protobuf:"varint,1,opt,name=reviewID,proto3" json:"reviewID,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditReviewReply) Reset() {
	*x = AuditReviewReply{}
	mi := &file_operation_v1_operation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditReviewReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditReviewReply) ProtoMessage() {}

func (x *AuditReviewReply) ProtoReflect() protoreflect.Message {
	mi := &file_operation_v1_operation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditReviewReply.ProtoReflect.Descriptor instead.
func (*AuditReviewReply) Descriptor() ([]byte, []int) {
	return file_operation_v1_operation_proto_rawDescGZIP(), []int{1}
}

func (x *AuditReviewReply) GetReviewID() int64 {
	if x != nil {
		return x.ReviewID
	}
	return 0
}

func (x *AuditReviewReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AuditAppealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppealID      int64                  `protobuf:"varint,1,opt,name=appealID,proto3" json:"appealID,omitempty"`
	Result        int32                  `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator      string                 `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditAppealRequest) Reset() {
	*x = AuditAppealRequest{}
	mi := &file_operation_v1_operation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditAppealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditAppealRequest) ProtoMessage() {}

func (x *AuditAppealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_v1_operation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditAppealRequest.ProtoReflect.Descriptor instead.
func (*AuditAppealRequest) Descriptor() ([]byte, []int) {
	return file_operation_v1_operation_proto_rawDescGZIP(), []int{2}
}

func (x *AuditAppealRequest) GetAppealID() int64 {
	if x != nil {
		return x.AppealID
	}
	return 0
}

func (x *AuditAppealRequest) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *AuditAppealRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *AuditAppealRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

type AuditAppealReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditAppealReply) Reset() {
	*x = AuditAppealReply{}
	mi := &file_operation_v1_operation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditAppealReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditAppealReply) ProtoMessage() {}

func (x *AuditAppealReply) ProtoReflect() protoreflect.Message {
	mi := &file_operation_v1_operation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditAppealReply.ProtoReflect.Descriptor instead.
func (*AuditAppealReply) Descriptor() ([]byte, []int) {
	return file_operation_v1_operation_proto_rawDescGZIP(), []int{3}
}

var File_operation_v1_operation_proto protoreflect.FileDescriptor

const file_operation_v1_operation_proto_rawDesc = "" +
	"\n" +
	"\x1coperation/v1/operation.proto\x12\x10api.operation.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xa6\x01\n" +
	"\x12AuditReviewRequest\x12#\n" +
	"\breviewID\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\breviewID\x12!\n" +
	"\x06result\x18\x02 \x01(\x05B\t\xfaB\x06\x1a\x040\x010\x02R\x06result\x12 \n" +
	"\x06remark\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x18\xd0\x0fR\x06remark\x12&\n" +
	"\boperator\x18\x04 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01R\boperator\"F\n" +
	"\x10AuditReviewReply\x12\x1a\n" +
	"\breviewID\x18\x01 \x01(\x03R\breviewID\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"\xa6\x01\n" +
	"\x12AuditAppealRequest\x12#\n" +
	"\bappealID\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\bappealID\x12!\n" +
	"\x06result\x18\x02 \x01(\x05B\t\xfaB\x06\x1a\x040\x010\x02R\x06result\x12 \n" +
	"\x06remark\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x18\xd0\x0fR\x06remark\x12&\n" +
	"\boperator\x18\x04 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01R\boperator\"\x12\n" +
	"\x10AuditAppealReply2\x84\x02\n" +
	"\tOperation\x12w\n" +
	"\vAuditReview\x12$.api.operation.v1.AuditReviewRequest\x1a\".api.operation.v1.AuditReviewReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/op/review/audit\x12~\n" +
	"\vAuditAppeal\x12$.api.operation.v1.AuditAppealRequest\x1a\".api.operation.v1.AuditAppealReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/op/review/appeal/auditB2\n" +
	"\x10api.operation.v1P\x01Z\x1creview-O/api/operation/v1;v1b\x06proto3"

var (
	file_operation_v1_operation_proto_rawDescOnce sync.Once
	file_operation_v1_operation_proto_rawDescData []byte
)

func file_operation_v1_operation_proto_rawDescGZIP() []byte {
	file_operation_v1_operation_proto_rawDescOnce.Do(func() {
		file_operation_v1_operation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_operation_v1_operation_proto_rawDesc), len(file_operation_v1_operation_proto_rawDesc)))
	})
	return file_operation_v1_operation_proto_rawDescData
}

var file_operation_v1_operation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_operation_v1_operation_proto_goTypes = []any{
	(*AuditReviewRequest)(nil), // 0: api.operation.v1.AuditReviewRequest
	(*AuditReviewReply)(nil),   // 1: api.operation.v1.AuditReviewReply
	(*AuditAppealRequest)(nil), // 2: api.operation.v1.AuditAppealRequest
	(*AuditAppealReply)(nil),   // 3: api.operation.v1.AuditAppealReply
}
var file_operation_v1_operation_proto_depIdxs = []int32{
	0, // 0: api.operation.v1.Operation.AuditReview:input_type -> api.operation.v1.AuditReviewRequest
	2, // 1: api.operation.v1.Operation.AuditAppeal:input_type -> api.operation.v1.AuditAppealRequest
	1, // 2: api.operation.v1.Operation.AuditReview:output_type -> api.operation.v1.AuditReviewReply
	3, // 3: api.operation.v1.Operation.AuditAppeal:output_type -> api.operation.v1.AuditAppealReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_operation_v1_operation_proto_init() }
func file_operation_v1_operation_proto_init() {
	if File_operation_v1_operation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_operation_v1_operation_proto_rawDesc), len(file_operation_v1_operation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_operation_v1_operation_proto_goTypes,
		DependencyIndexes: file_operation_v1_operation_proto_depIdxs,
		MessageInfos:      file_operation_v1_operation_proto_msgTypes,
	}.Build()
	File_operation_v1_operation_proto = out.File
	file_operation_v1_operation_proto_goTypes = nil
	file_operation_v1_operation_proto_depIdxs = nil
}
