// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 参数非法（校验失败、缺字段等）
func IsInvalidParameter(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ReviewErrorReason_INVALID_PARAMETER.String() && e.Code == 400
}

// 参数非法（校验失败、缺字段等）
func ErrorInvalidParameter(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ReviewErrorReason_INVALID_PARAMETER.String(), fmt.Sprintf(format, args...))
}

// 订单已存在评价
func IsOrderAlreadyReviewed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ReviewErrorReason_ORDER_ALREADY_REVIEWED.String() && e.Code == 400
}

// 订单已存在评价
func ErrorOrderAlreadyReviewed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ReviewErrorReason_ORDER_ALREADY_REVIEWED.String(), fmt.Sprintf(format, args...))
}

// 评价不存在
func IsReviewNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ReviewErrorReason_REVIEW_NOT_FOUND.String() && e.Code == 404
}

// 评价不存在
func ErrorReviewNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ReviewErrorReason_REVIEW_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

// 无权限操作该评价（用户/店铺不匹配等）
func IsForbidden(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ReviewErrorReason_FORBIDDEN.String() && e.Code == 403
}

// 无权限操作该评价（用户/店铺不匹配等）
func ErrorForbidden(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ReviewErrorReason_FORBIDDEN.String(), fmt.Sprintf(format, args...))
}

// 评价状态不允许当前操作
func IsReviewStatusInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ReviewErrorReason_REVIEW_STATUS_INVALID.String() && e.Code == 409
}

// 评价状态不允许当前操作
func ErrorReviewStatusInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ReviewErrorReason_REVIEW_STATUS_INVALID.String(), fmt.Sprintf(format, args...))
}

// 数据库或持久化失败
func IsDatabaseError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ReviewErrorReason_DATABASE_ERROR.String() && e.Code == 500
}

// 数据库或持久化失败
func ErrorDatabaseError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ReviewErrorReason_DATABASE_ERROR.String(), fmt.Sprintf(format, args...))
}

// 未归类内部错误
func IsInternalError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ReviewErrorReason_INTERNAL_ERROR.String() && e.Code == 500
}

// 未归类内部错误
func ErrorInternalError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ReviewErrorReason_INTERNAL_ERROR.String(), fmt.Sprintf(format, args...))
}
