// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: review/v1/review_error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Review 业务错误码，供 protoc-gen-go-errors 生成 IsXxx / ErrorXxx
type ReviewErrorReason int32

const (
	ReviewErrorReason_REVIEW_UNSPECIFIED ReviewErrorReason = 0
	// 参数非法（校验失败、缺字段等）
	ReviewErrorReason_INVALID_PARAMETER ReviewErrorReason = 1
	// 订单已存在评价
	ReviewErrorReason_ORDER_ALREADY_REVIEWED ReviewErrorReason = 2
	// 评价不存在
	ReviewErrorReason_REVIEW_NOT_FOUND ReviewErrorReason = 3
	// 无权限操作该评价（用户/店铺不匹配等）
	ReviewErrorReason_FORBIDDEN ReviewErrorReason = 4
	// 评价状态不允许当前操作
	ReviewErrorReason_REVIEW_STATUS_INVALID ReviewErrorReason = 5
	// 数据库或持久化失败
	ReviewErrorReason_DATABASE_ERROR ReviewErrorReason = 6
	// 未归类内部错误
	ReviewErrorReason_INTERNAL_ERROR ReviewErrorReason = 7
)

// Enum value maps for ReviewErrorReason.
var (
	ReviewErrorReason_name = map[int32]string{
		0: "REVIEW_UNSPECIFIED",
		1: "INVALID_PARAMETER",
		2: "ORDER_ALREADY_REVIEWED",
		3: "REVIEW_NOT_FOUND",
		4: "FORBIDDEN",
		5: "REVIEW_STATUS_INVALID",
		6: "DATABASE_ERROR",
		7: "INTERNAL_ERROR",
	}
	ReviewErrorReason_value = map[string]int32{
		"REVIEW_UNSPECIFIED":     0,
		"INVALID_PARAMETER":      1,
		"ORDER_ALREADY_REVIEWED": 2,
		"REVIEW_NOT_FOUND":       3,
		"FORBIDDEN":              4,
		"REVIEW_STATUS_INVALID":  5,
		"DATABASE_ERROR":         6,
		"INTERNAL_ERROR":         7,
	}
)

func (x ReviewErrorReason) Enum() *ReviewErrorReason {
	p := new(ReviewErrorReason)
	*p = x
	return p
}

func (x ReviewErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReviewErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_review_v1_review_error_reason_proto_enumTypes[0].Descriptor()
}

func (ReviewErrorReason) Type() protoreflect.EnumType {
	return &file_review_v1_review_error_reason_proto_enumTypes[0]
}

func (x ReviewErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReviewErrorReason.Descriptor instead.
func (ReviewErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_review_v1_review_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_review_v1_review_error_reason_proto protoreflect.FileDescriptor

const file_review_v1_review_error_reason_proto_rawDesc = "" +
	"\n" +
	"#review/v1/review_error_reason.proto\x12\rapi.review.v1\x1a\x13errors/errors.proto*\xf5\x01\n" +
	"\x11ReviewErrorReason\x12\x1b\n" +
	"\x12REVIEW_UNSPECIFIED\x10\x00\x1a\x03\xa8E\x00\x12\x1b\n" +
	"\x11INVALID_PARAMETER\x10\x01\x1a\x04\xa8E\x90\x03\x12 \n" +
	"\x16ORDER_ALREADY_REVIEWED\x10\x02\x1a\x04\xa8E\x90\x03\x12\x1a\n" +
	"\x10REVIEW_NOT_FOUND\x10\x03\x1a\x04\xa8E\x94\x03\x12\x13\n" +
	"\tFORBIDDEN\x10\x04\x1a\x04\xa8E\x93\x03\x12\x1f\n" +
	"\x15REVIEW_STATUS_INVALID\x10\x05\x1a\x04\xa8E\x99\x03\x12\x18\n" +
	"\x0eDATABASE_ERROR\x10\x06\x1a\x04\xa8E\xf4\x03\x12\x18\n" +
	"\x0eINTERNAL_ERROR\x10\a\x1a\x04\xa8E\xf4\x03B!Z\x1freview-service/api/review/v1;v1b\x06proto3"

var (
	file_review_v1_review_error_reason_proto_rawDescOnce sync.Once
	file_review_v1_review_error_reason_proto_rawDescData []byte
)

func file_review_v1_review_error_reason_proto_rawDescGZIP() []byte {
	file_review_v1_review_error_reason_proto_rawDescOnce.Do(func() {
		file_review_v1_review_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_review_v1_review_error_reason_proto_rawDesc), len(file_review_v1_review_error_reason_proto_rawDesc)))
	})
	return file_review_v1_review_error_reason_proto_rawDescData
}

var file_review_v1_review_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_review_v1_review_error_reason_proto_goTypes = []any{
	(ReviewErrorReason)(0), // 0: api.review.v1.ReviewErrorReason
}
var file_review_v1_review_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_review_v1_review_error_reason_proto_init() }
func file_review_v1_review_error_reason_proto_init() {
	if File_review_v1_review_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_review_v1_review_error_reason_proto_rawDesc), len(file_review_v1_review_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_review_v1_review_error_reason_proto_goTypes,
		DependencyIndexes: file_review_v1_review_error_reason_proto_depIdxs,
		EnumInfos:         file_review_v1_review_error_reason_proto_enumTypes,
	}.Build()
	File_review_v1_review_error_reason_proto = out.File
	file_review_v1_review_error_reason_proto_goTypes = nil
	file_review_v1_review_error_reason_proto_depIdxs = nil
}
