// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: comment/v1/comment.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 评论所挂载的内容类型（知乎：问题 / 回答 / 文章 / 想法等，可按产品扩展）
type CommentTargetType int32

const (
	CommentTargetType_COMMENT_TARGET_TYPE_UNSPECIFIED CommentTargetType = 0
	CommentTargetType_COMMENT_TARGET_TYPE_QUESTION    CommentTargetType = 1
	CommentTargetType_COMMENT_TARGET_TYPE_ANSWER      CommentTargetType = 2
	CommentTargetType_COMMENT_TARGET_TYPE_ARTICLE     CommentTargetType = 3
	CommentTargetType_COMMENT_TARGET_TYPE_PIN         CommentTargetType = 4 // 想法/动态类内容
)

// Enum value maps for CommentTargetType.
var (
	CommentTargetType_name = map[int32]string{
		0: "COMMENT_TARGET_TYPE_UNSPECIFIED",
		1: "COMMENT_TARGET_TYPE_QUESTION",
		2: "COMMENT_TARGET_TYPE_ANSWER",
		3: "COMMENT_TARGET_TYPE_ARTICLE",
		4: "COMMENT_TARGET_TYPE_PIN",
	}
	CommentTargetType_value = map[string]int32{
		"COMMENT_TARGET_TYPE_UNSPECIFIED": 0,
		"COMMENT_TARGET_TYPE_QUESTION":    1,
		"COMMENT_TARGET_TYPE_ANSWER":      2,
		"COMMENT_TARGET_TYPE_ARTICLE":     3,
		"COMMENT_TARGET_TYPE_PIN":         4,
	}
)

func (x CommentTargetType) Enum() *CommentTargetType {
	p := new(CommentTargetType)
	*p = x
	return p
}

func (x CommentTargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommentTargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_comment_v1_comment_proto_enumTypes[0].Descriptor()
}

func (CommentTargetType) Type() protoreflect.EnumType {
	return &file_comment_v1_comment_proto_enumTypes[0]
}

func (x CommentTargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommentTargetType.Descriptor instead.
func (CommentTargetType) EnumDescriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{0}
}

type CommentSort int32

const (
	CommentSort_COMMENT_SORT_UNSPECIFIED     CommentSort = 0
	CommentSort_COMMENT_SORT_CREATED_AT_ASC  CommentSort = 1
	CommentSort_COMMENT_SORT_CREATED_AT_DESC CommentSort = 2
	CommentSort_COMMENT_SORT_HOT             CommentSort = 3
)

// Enum value maps for CommentSort.
var (
	CommentSort_name = map[int32]string{
		0: "COMMENT_SORT_UNSPECIFIED",
		1: "COMMENT_SORT_CREATED_AT_ASC",
		2: "COMMENT_SORT_CREATED_AT_DESC",
		3: "COMMENT_SORT_HOT",
	}
	CommentSort_value = map[string]int32{
		"COMMENT_SORT_UNSPECIFIED":     0,
		"COMMENT_SORT_CREATED_AT_ASC":  1,
		"COMMENT_SORT_CREATED_AT_DESC": 2,
		"COMMENT_SORT_HOT":             3,
	}
)

func (x CommentSort) Enum() *CommentSort {
	p := new(CommentSort)
	*p = x
	return p
}

func (x CommentSort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommentSort) Descriptor() protoreflect.EnumDescriptor {
	return file_comment_v1_comment_proto_enumTypes[1].Descriptor()
}

func (CommentSort) Type() protoreflect.EnumType {
	return &file_comment_v1_comment_proto_enumTypes[1]
}

func (x CommentSort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommentSort.Descriptor instead.
func (CommentSort) EnumDescriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{1}
}

type CreateCommentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetType     CommentTargetType      `protobuf:"varint,1,opt,name=target_type,json=targetType,proto3,enum=api.comment.v1.CommentTargetType" json:"target_type,omitempty"`
	TargetId       int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	ParentId       int64                  `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`                    // 0 表示顶层评论；否则为父评论 id
	ReplyToUserId  int64                  `protobuf:"varint,4,opt,name=reply_to_user_id,json=replyToUserId,proto3" json:"reply_to_user_id,omitempty"` // 可选，展示「回复 @某人」
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	AttachmentUrls []string               `protobuf:"bytes,6,rep,name=attachment_urls,json=attachmentUrls,proto3" json:"attachment_urls,omitempty"` // 可选，图片等
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_comment_v1_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCommentRequest) GetTargetType() CommentTargetType {
	if x != nil {
		return x.TargetType
	}
	return CommentTargetType_COMMENT_TARGET_TYPE_UNSPECIFIED
}

func (x *CreateCommentRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *CreateCommentRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateCommentRequest) GetReplyToUserId() int64 {
	if x != nil {
		return x.ReplyToUserId
	}
	return 0
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCommentRequest) GetAttachmentUrls() []string {
	if x != nil {
		return x.AttachmentUrls
	}
	return nil
}

type CreateCommentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentReply) Reset() {
	*x = CreateCommentReply{}
	mi := &file_comment_v1_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentReply) ProtoMessage() {}

func (x *CreateCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentReply.ProtoReflect.Descriptor instead.
func (*CreateCommentReply) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCommentReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentRequest) Reset() {
	*x = UpdateCommentRequest{}
	mi := &file_comment_v1_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentRequest) ProtoMessage() {}

func (x *UpdateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCommentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateCommentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentReply) Reset() {
	*x = UpdateCommentReply{}
	mi := &file_comment_v1_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentReply) ProtoMessage() {}

func (x *UpdateCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentReply.ProtoReflect.Descriptor instead.
func (*UpdateCommentReply) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{3}
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_comment_v1_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCommentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCommentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentReply) Reset() {
	*x = DeleteCommentReply{}
	mi := &file_comment_v1_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentReply) ProtoMessage() {}

func (x *DeleteCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentReply.ProtoReflect.Descriptor instead.
func (*DeleteCommentReply) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{5}
}

type GetCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentRequest) Reset() {
	*x = GetCommentRequest{}
	mi := &file_comment_v1_comment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentRequest) ProtoMessage() {}

func (x *GetCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentRequest.ProtoReflect.Descriptor instead.
func (*GetCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{6}
}

func (x *GetCommentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCommentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentReply) Reset() {
	*x = GetCommentReply{}
	mi := &file_comment_v1_comment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentReply) ProtoMessage() {}

func (x *GetCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentReply.ProtoReflect.Descriptor instead.
func (*GetCommentReply) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{7}
}

func (x *GetCommentReply) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type ListCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetType    CommentTargetType      `protobuf:"varint,1,opt,name=target_type,json=targetType,proto3,enum=api.comment.v1.CommentTargetType" json:"target_type,omitempty"`
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	ParentId      int64                  `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // 0 顶层；非 0 某条的子评论列表
	Sort          CommentSort            `protobuf:"varint,4,opt,name=sort,proto3,enum=api.comment.v1.CommentSort" json:"sort,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsRequest) Reset() {
	*x = ListCommentsRequest{}
	mi := &file_comment_v1_comment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsRequest) ProtoMessage() {}

func (x *ListCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{8}
}

func (x *ListCommentsRequest) GetTargetType() CommentTargetType {
	if x != nil {
		return x.TargetType
	}
	return CommentTargetType_COMMENT_TARGET_TYPE_UNSPECIFIED
}

func (x *ListCommentsRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ListCommentsRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *ListCommentsRequest) GetSort() CommentSort {
	if x != nil {
		return x.Sort
	}
	return CommentSort_COMMENT_SORT_UNSPECIFIED
}

func (x *ListCommentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCommentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListCommentsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"` // 可选，列表总数（分页 UI）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsReply) Reset() {
	*x = ListCommentsReply{}
	mi := &file_comment_v1_comment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsReply) ProtoMessage() {}

func (x *ListCommentsReply) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsReply.ProtoReflect.Descriptor instead.
func (*ListCommentsReply) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{9}
}

func (x *ListCommentsReply) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ListCommentsReply) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListCommentsReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Comment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorUserId   int64                  `protobuf:"varint,2,opt,name=author_user_id,json=authorUserId,proto3" json:"author_user_id,omitempty"`
	TargetType     CommentTargetType      `protobuf:"varint,3,opt,name=target_type,json=targetType,proto3,enum=api.comment.v1.CommentTargetType" json:"target_type,omitempty"`
	TargetId       int64                  `protobuf:"varint,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	ParentId       int64                  `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ReplyToUserId  int64                  `protobuf:"varint,6,opt,name=reply_to_user_id,json=replyToUserId,proto3" json:"reply_to_user_id,omitempty"`
	Content        string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	ReplyCount     int32                  `protobuf:"varint,8,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`
	LikeCount      int32                  `protobuf:"varint,9,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	AttachmentUrls []string               `protobuf:"bytes,10,rep,name=attachment_urls,json=attachmentUrls,proto3" json:"attachment_urls,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_comment_v1_comment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{10}
}

func (x *Comment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetAuthorUserId() int64 {
	if x != nil {
		return x.AuthorUserId
	}
	return 0
}

func (x *Comment) GetTargetType() CommentTargetType {
	if x != nil {
		return x.TargetType
	}
	return CommentTargetType_COMMENT_TARGET_TYPE_UNSPECIFIED
}

func (x *Comment) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *Comment) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Comment) GetReplyToUserId() int64 {
	if x != nil {
		return x.ReplyToUserId
	}
	return 0
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *Comment) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Comment) GetAttachmentUrls() []string {
	if x != nil {
		return x.AttachmentUrls
	}
	return nil
}

func (x *Comment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Comment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_comment_v1_comment_proto protoreflect.FileDescriptor

const file_comment_v1_comment_proto_rawDesc = "" +
	"\n" +
	"\x18comment/v1/comment.proto\x12\x0eapi.comment.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x02\n" +
	"\x14CreateCommentRequest\x12B\n" +
	"\vtarget_type\x18\x01 \x01(\x0e2!.api.comment.v1.CommentTargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\x03R\bparentId\x12'\n" +
	"\x10reply_to_user_id\x18\x04 \x01(\x03R\rreplyToUserId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12'\n" +
	"\x0fattachment_urls\x18\x06 \x03(\tR\x0eattachmentUrls\"$\n" +
	"\x12CreateCommentReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"@\n" +
	"\x14UpdateCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x14\n" +
	"\x12UpdateCommentReply\"&\n" +
	"\x14DeleteCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12DeleteCommentReply\"#\n" +
	"\x11GetCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"D\n" +
	"\x0fGetCommentReply\x121\n" +
	"\acomment\x18\x01 \x01(\v2\x17.api.comment.v1.CommentR\acomment\"\x80\x02\n" +
	"\x13ListCommentsRequest\x12B\n" +
	"\vtarget_type\x18\x01 \x01(\x0e2!.api.comment.v1.CommentTargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\x03R\bparentId\x12/\n" +
	"\x04sort\x18\x04 \x01(\x0e2\x1b.api.comment.v1.CommentSortR\x04sort\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageToken\"\x86\x01\n" +
	"\x11ListCommentsReply\x123\n" +
	"\bcomments\x18\x01 \x03(\v2\x17.api.comment.v1.CommentR\bcomments\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"\xdf\x03\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12$\n" +
	"\x0eauthor_user_id\x18\x02 \x01(\x03R\fauthorUserId\x12B\n" +
	"\vtarget_type\x18\x03 \x01(\x0e2!.api.comment.v1.CommentTargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\x03R\btargetId\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\x03R\bparentId\x12'\n" +
	"\x10reply_to_user_id\x18\x06 \x01(\x03R\rreplyToUserId\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x1f\n" +
	"\vreply_count\x18\b \x01(\x05R\n" +
	"replyCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\t \x01(\x05R\tlikeCount\x12'\n" +
	"\x0fattachment_urls\x18\n" +
	" \x03(\tR\x0eattachmentUrls\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\xb8\x01\n" +
	"\x11CommentTargetType\x12#\n" +
	"\x1fCOMMENT_TARGET_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCOMMENT_TARGET_TYPE_QUESTION\x10\x01\x12\x1e\n" +
	"\x1aCOMMENT_TARGET_TYPE_ANSWER\x10\x02\x12\x1f\n" +
	"\x1bCOMMENT_TARGET_TYPE_ARTICLE\x10\x03\x12\x1b\n" +
	"\x17COMMENT_TARGET_TYPE_PIN\x10\x04*\x84\x01\n" +
	"\vCommentSort\x12\x1c\n" +
	"\x18COMMENT_SORT_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCOMMENT_SORT_CREATED_AT_ASC\x10\x01\x12 \n" +
	"\x1cCOMMENT_SORT_CREATED_AT_DESC\x10\x02\x12\x14\n" +
	"\x10COMMENT_SORT_HOT\x10\x032\xce\x04\n" +
	"\x0eCommentService\x12r\n" +
	"\rCreateComment\x12$.api.comment.v1.CreateCommentRequest\x1a\".api.comment.v1.CreateCommentReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/comments\x12w\n" +
	"\rUpdateComment\x12$.api.comment.v1.UpdateCommentRequest\x1a\".api.comment.v1.UpdateCommentReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/v1/comments/{id}\x12t\n" +
	"\rDeleteComment\x12$.api.comment.v1.DeleteCommentRequest\x1a\".api.comment.v1.DeleteCommentReply\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/comments/{id}\x12k\n" +
	"\n" +
	"GetComment\x12!.api.comment.v1.GetCommentRequest\x1a\x1f.api.comment.v1.GetCommentReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/comments/{id}\x12l\n" +
	"\fListComments\x12#.api.comment.v1.ListCommentsRequest\x1a!.api.comment.v1.ListCommentsReply\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/commentsB4\n" +
	"\x0eapi.comment.v1P\x01Z review-service/api/comment/v1;v1b\x06proto3"

var (
	file_comment_v1_comment_proto_rawDescOnce sync.Once
	file_comment_v1_comment_proto_rawDescData []byte
)

func file_comment_v1_comment_proto_rawDescGZIP() []byte {
	file_comment_v1_comment_proto_rawDescOnce.Do(func() {
		file_comment_v1_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comment_v1_comment_proto_rawDesc), len(file_comment_v1_comment_proto_rawDesc)))
	})
	return file_comment_v1_comment_proto_rawDescData
}

var file_comment_v1_comment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_comment_v1_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_comment_v1_comment_proto_goTypes = []any{
	(CommentTargetType)(0),        // 0: api.comment.v1.CommentTargetType
	(CommentSort)(0),              // 1: api.comment.v1.CommentSort
	(*CreateCommentRequest)(nil),  // 2: api.comment.v1.CreateCommentRequest
	(*CreateCommentReply)(nil),    // 3: api.comment.v1.CreateCommentReply
	(*UpdateCommentRequest)(nil),  // 4: api.comment.v1.UpdateCommentRequest
	(*UpdateCommentReply)(nil),    // 5: api.comment.v1.UpdateCommentReply
	(*DeleteCommentRequest)(nil),  // 6: api.comment.v1.DeleteCommentRequest
	(*DeleteCommentReply)(nil),    // 7: api.comment.v1.DeleteCommentReply
	(*GetCommentRequest)(nil),     // 8: api.comment.v1.GetCommentRequest
	(*GetCommentReply)(nil),       // 9: api.comment.v1.GetCommentReply
	(*ListCommentsRequest)(nil),   // 10: api.comment.v1.ListCommentsRequest
	(*ListCommentsReply)(nil),     // 11: api.comment.v1.ListCommentsReply
	(*Comment)(nil),               // 12: api.comment.v1.Comment
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_comment_v1_comment_proto_depIdxs = []int32{
	0,  // 0: api.comment.v1.CreateCommentRequest.target_type:type_name -> api.comment.v1.CommentTargetType
	12, // 1: api.comment.v1.GetCommentReply.comment:type_name -> api.comment.v1.Comment
	0,  // 2: api.comment.v1.ListCommentsRequest.target_type:type_name -> api.comment.v1.CommentTargetType
	1,  // 3: api.comment.v1.ListCommentsRequest.sort:type_name -> api.comment.v1.CommentSort
	12, // 4: api.comment.v1.ListCommentsReply.comments:type_name -> api.comment.v1.Comment
	0,  // 5: api.comment.v1.Comment.target_type:type_name -> api.comment.v1.CommentTargetType
	13, // 6: api.comment.v1.Comment.created_at:type_name -> google.protobuf.Timestamp
	13, // 7: api.comment.v1.Comment.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 8: api.comment.v1.CommentService.CreateComment:input_type -> api.comment.v1.CreateCommentRequest
	4,  // 9: api.comment.v1.CommentService.UpdateComment:input_type -> api.comment.v1.UpdateCommentRequest
	6,  // 10: api.comment.v1.CommentService.DeleteComment:input_type -> api.comment.v1.DeleteCommentRequest
	8,  // 11: api.comment.v1.CommentService.GetComment:input_type -> api.comment.v1.GetCommentRequest
	10, // 12: api.comment.v1.CommentService.ListComments:input_type -> api.comment.v1.ListCommentsRequest
	3,  // 13: api.comment.v1.CommentService.CreateComment:output_type -> api.comment.v1.CreateCommentReply
	5,  // 14: api.comment.v1.CommentService.UpdateComment:output_type -> api.comment.v1.UpdateCommentReply
	7,  // 15: api.comment.v1.CommentService.DeleteComment:output_type -> api.comment.v1.DeleteCommentReply
	9,  // 16: api.comment.v1.CommentService.GetComment:output_type -> api.comment.v1.GetCommentReply
	11, // 17: api.comment.v1.CommentService.ListComments:output_type -> api.comment.v1.ListCommentsReply
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_comment_v1_comment_proto_init() }
func file_comment_v1_comment_proto_init() {
	if File_comment_v1_comment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comment_v1_comment_proto_rawDesc), len(file_comment_v1_comment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comment_v1_comment_proto_goTypes,
		DependencyIndexes: file_comment_v1_comment_proto_depIdxs,
		EnumInfos:         file_comment_v1_comment_proto_enumTypes,
		MessageInfos:      file_comment_v1_comment_proto_msgTypes,
	}.Build()
	File_comment_v1_comment_proto = out.File
	file_comment_v1_comment_proto_goTypes = nil
	file_comment_v1_comment_proto_depIdxs = nil
}
